name: Build and Deploy to Argo CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout flask-app repo
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: yourdockerhubid/flask-app:latest

    - name: Update image tag in k8s repo
      run: |
        git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/yourname/flask-k8s-deploy.git
        cd flask-k8s-deploy
        sed -i 's|newTag:.*|newTag: latest|' kustomization.yaml
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "Update image tag"
        git push

